name: Changelog

on:
  workflow_dispatch:
  # Trigger analysis when pushing in master or pull requests,
  # and when creating a pull request.
  release:
    types:
      - published

jobs:
  changelog:
    name: Update changelog
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: main
      - name: Changelog
        uses: rhysd/changelog-from-release/action@78b335bb7d059f35ad04c5428d50711726feee50 # v3.9.1
        with:
          file: CHANGELOG.md
          github_token: ${{ secrets.GITHUB_TOKEN }}
