name: PR check

on:
  workflow_dispatch:
  # Trigger analysis when pushing in master or pull requests,
  # and when creating a pull request.
  push:
    branches:
      - master
      - feature*

  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  tests:
    name: Coverage
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x]
        mongoose-version: [mongoose@6.12.2, mongoose@7.6.4, mongoose@latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm

      - name: Installing dependencies
        run: npm ci

      - name: Installing ${{ matrix.mongoose-version }}
        run: npm i ${{ matrix.mongoose-version }}

      - name: Coverage
        run: npm run test
  sonar:
    name: Biome, Coverage & Sonar
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm

      - name: Installing dependencies
        run: npm ci

      - name: Biome
        run: npm run biome

      - name: Coverage
        run: npm run test

      - name: Scan
        if: env.SONAR_TOKEN
        uses: SonarSource/sonarqube-scan-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.organization=ilovepixelart
            -Dsonar.projectName=ts-patch-mongoose
            -Dsonar.projectKey=ilovepixelart_ts-patch-mongoose
            -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info
            -Dsonar.sources=src
            -Dsonar.tests=tests
            -Dsonar.test.exclusions=tests/**
            -Dsonar.coverage.exclusions=tests/**
